package pl.sdacademy.enums;

public enum State {
    INIT,
    LOGGING_IN_AS_ADMIN,
    LOGGING_IN_AS_ACCOUNTANT,
    LOGGED_IN_AS_ADMIN,
    LOGGED_IN_AS_ACCOUNTANT,
    MANAGING_COMPANIES,
    MANAGING_ADMINS,
    MANAGING_ACCOUNTANTS,
    CREATING_COMPANY,
    EXIT,
    LOGGING_TO_COMPANY_MANAGEMENT,
    MANAGING_COMPANY_INVOICING,
    ADDING_SELL_INVOICE,
    ADDING_PURCHASE_INVOICE,
    VIEWING_PURCHASE_INVOICE,
    VIEWING_SELL_INVOICE
}
